name: teleoscope
channels:
  - conda-forge
  - defaults
dependencies:
  - bcrypt=3.2.0
  - blas
  - brotli-python
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - click
  - cryptography
  - cython
  - greenlet
  - hdbscan
  - idna
  - iniconfig
  - joblib
  - libblas
  - libcblas
  - libcxx
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - liblapack
  - libllvm14
  - libopenblas
  - libsqlite
  - libzlib
  - llvm-openmp
  - llvmlite
  - mongomock
  - ncurses
  - numba
  - numpy
  - numpy-base
  - openssl
  - packaging
  - pika
  - pip
  - platformdirs
  - pluggy
  - pooch
  - pycparser
  - pynndescent
  - pyopenssl
  - pysocks
  - pytest
  - python
  - python_abi
  - pytz
  - pyyaml
  - readline
  - scikit-learn
  - scipy
  - sentinels
  - setuptools
  - simplejson
  - six
  - sqlalchemy
  - tbb
  - threadpoolctl
  - tk
  - typing-extensions
  - typing_extensions
  - umap-learn
  - urllib3
  - wheel
  - xz
  - yaml
  - pip:
      - accelerate
      - aiohttp
      - aiosignal
      - amqp
      - annotated-types
      - argon2-cffi
      - argon2-cffi-bindings
      - attrs
      - billiard
      - blis
      - catalogue
      - celery
      - click-didyoumean
      - click-plugins
      - click-repl
      - cloudpathlib
      - coloredlogs
      - confection
      - cymem
      - datasets
      - dill
      - dnspython
      - en-core-web-sm
      - environs
      - filelock
      - flagembedding
      - flatbuffers
      - frozenlist
      - fsspec
      - grpcio
      - huggingface-hub
      - humanfriendly
      - jinja2
      - kombu
      - langcodes
      - language-data
      - marisa-trie
      - markdown-it-py
      - markupsafe
      - marshmallow
      - mdurl
      - milvus-lite
      - milvus-model
      - minio
      - mpmath
      - multidict
      - multiprocess
      - murmurhash
      - networkx
      - nltk
      - onnxruntime
      - pandas
      - pillow
      - preshed
      - prompt-toolkit
      - protobuf
      - psutil
      - pyarrow
      - pyarrow-hotfix
      - pycryptodome
      - pydantic
      - pydantic-core
      - pygments
      - pymilvus
      - pymongo
      - python-dateutil
      - python-dotenv
      - random-object-id
      - regex
      - requests
      - rich
      - safetensors
      - sentence-transformers
      - shellingham
      - smart-open
      - spacy
      - spacy-legacy
      - spacy-loggers
      - srsly
      - sympy
      - thinc
      - tokenizers
      - torch
      - tqdm
      - transformers
      - typer
      - tzdata
      - ujson
      - vine
      - wasabi
      - wcwidth
      - weasel
      - wrapt
      - xxhash
      - yarl
prefix: ~/miniconda3/envs/teleoscope
